### ISSUE TITLE
Platforms supported 

### ISSUE THREAD

**Issue by JonnyTech** [DJMaster/ffmpeg-fpc#1]
Hi, are these bindings cross-platform? I see references to .dll files so I suspect that they are for Windows only. Can you confirm?

**Comment by DJMaster** [comment]
Hi JonnyTech,
these bindings are mainly developed under Windows, but other platforms can be supported as well, take a look at this commit for example: https://github.com/DJMaster/csfml-fpc/commit/2e9832451965927ff4defa6780be61abab896850

**ffmpeg-fpc** bindings are still under development, feel free to send pull requests, comments or suggestions.

Thank you.

**Comment by JonnyTech** [comment]
Thanks for the quick reply and the pointer to your other repository. I am trying to get back into development and fpc (primarily Linux based) so when I find some time will try cfsml before attempting anything more advanced. I shall certainly contribute back whatever I can.
